---
name: Build

on:
  pull_request:
  push:
    branches:
      - main
    tags:
      - 'v*'
  schedule:
    - cron: "0 0 * * 0"

jobs:
  # Test the image builds and works correctly.
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repo at current context
        uses: actions/checkout@v2

      - name: Install test dependencies
        run: ./tasks.sh test:install-depends

      - name: Run static code tests
        run: |
          ./tasks.sh -e test:lint
          ./tasks.sh -e test:units

      - name: Test building image
        run: docker build -t docker-buoy .

      - name: Run the built image
        run: docker run --name test-container -d docker-buoy

      - name: Verify Flask is accessible in the built image
        run: docker exec --tty test-container flask --version

  # On main branch only, build and release images.
  release:
    name: Release
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout the repo at current context
        uses: actions/checkout@v2

      - name: Set up Docker metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: bcbrookman/buoy
          tags: |
            type=raw, value=latest
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v3
        with:
          context: ./
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
