---
name: Build

on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * 0"

jobs:
  # Test the image builds and works correctly.
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repo at current context
        uses: actions/checkout@v2

      - name: Test building image
        run: docker build -t docker-buoy .

      - name: Run the built image
        run: docker run --name test-container -d docker-buoy

      - name: Verify Flask is accessible in the built image
        run: docker exec --tty test-container flask --version

  # If on main branch, build and release image.
  release:
    name: Release
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: bcbrookman/buoy
    
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      
      - name: Set up Docker Buildx
      - uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: bcbrookman/buoy:latest
